fastlane_version "1.110.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    cocoapods
    
  end

  desc "Runs all the tests"
  lane :test do
    scan
    slather(
      output_directory: "coverage",
      workspace: "Appetit.xcworkspace",
      scheme: "Appetit",
      proj: "Appetit.xcodeproj",
      html: true,
      ignore: [
        "**/Storyboard.swift",
        "**/AppetitAPI.swift",
        "**/AppetitAPIManager.swift"
      ]
    )
  end
end
